name: Update Readme Only

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - apps/readme/template.md

jobs:
  readme:
    name: Readme Only
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Turborepo Magic
        run: GH_PAT=${{ secrets.GH_PAT }} pnpm turbo --filter=@leomotors/readme post-analyze

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update Readme"
          default_author: github_actions
