name: Update Data

on:
  schedule:
    # * Runs at 4AM Everyday
    - cron: 0 21 * * *

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/run.yml

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: leomotors

    steps:
    - uses: actions/checkout@v2

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'

    # Cache dependencies. From:
    # https://github.com/actions/cache/blob/master/examples.md#python---pip
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r apps/github-stats/requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        cd apps/github-stats
        python3 --version
        python3 generate_images.py
        mkdir -p ../../generated
        mv generated/* ../../generated
      env:
        ACCESS_TOKEN: ${{ secrets.GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDE_FORKED_REPOS: true

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install Dependencies
      run: pnpm install

    - name: Language Stats, Turborepo Magic
      run: GH_PAT=${{ secrets.GH_PAT }} pnpm analyze

    - name: Push data to branches
      uses: JamesIves/github-pages-deploy-action@4.4.0
      with:
        branch: generated
        folder: generated
        git-config-name: github-actions
        git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
        commit-message: Update Generated Data ✨
