name: Update All Data

on:
  schedule:
    # * Runs at 4AM Everyday
    - cron: 0 21 * * *

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - .github/workflows/run.yml

jobs:
  stats:
    name: All
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Run using Python 3.8 for consistency and aiohttp
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Cache dependencies. From:
      # https://github.com/actions/cache/blob/master/examples.md#python---pip
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies with `pip`
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r apps/github-stats/requirements.txt

      # Generate all statistics images
      - name: Generate images
        run: |
          cd apps/github-stats
          python3 generate_images.py
          mkdir -p ../../generated
          mv generated/* ../../generated
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EXCLUDE_FORKED_REPOS: true
          EXCLUDED_LANGS: Jupyter Notebook

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Turborepo Magic
        run: GH_PAT=${{ secrets.GH_PAT }} pnpm post-analyze

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update Generated Data and Readme"
          default_author: github_actions
