name: Update Data

on:
  schedule:
    # * Runs at 4AM Everyday
    - cron: 0 21 * * *

  workflow_dispatch:

jobs:
  updarte:
    name: Update Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v2

      - name: Install Dependencies (Yarn)
        run: yarn install

      - name: Turborepo Magic
        run: GH_PAT=${{ secrets.GH_PAT }} yarn analyze

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "[SKIP BUILD] Update Language Stats Data"
          default_author: github_actions
